[2025-08-30 21:30:33,896] [ERROR] - custom_exception.py (line:33) - 
        DocumentPortalException occurred:
        File: C:\Users\Kranthi\OneDrive\Desktop\LLMOPS_Krishnaik\Projects\Document_Portal\exception\custom_exception.py
        Line: 29
        Message: division by zero
        Traceback:
        Traceback (most recent call last):
  File "C:\Users\Kranthi\OneDrive\Desktop\LLMOPS_Krishnaik\Projects\Document_Portal\exception\custom_exception.py", line 29, in <module>
    a = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero

        
